***Total: 42 points***

Complete this homework by writing R code to complete the following tasks. Keep in mind:

i. Empty chunks have been included where code is required
ii. This homework requires use of data files:

  - `BRCA.genome_wide_snp_6_broad_Level_3_scna.seg` (Problems 1, 2)
  - `GIAB_highconf_v.3.3.2.vcf.gz` (Problem 3)
  
iv. You will be graded on your code and output results. The assignment is worth 42 points total; partial credit can be awarded.

For additional resources, please refer to these links:  
Problems 1 & 2:  
  - https://www.bioconductor.org/packages/devel/bioc/vignettes/plyranges/inst/doc/an-introduction.html
  - https://bioconductor.org/packages/release/bioc/vignettes/GenomicRanges/inst/doc/GenomicRangesIntroduction.html  
Problem 3:  
  - https://bioconductor.org/packages/release/bioc/vignettes/Rsamtools/inst/doc/Rsamtools-Overview.pdf  
Problem 4: 
  - https://bioconductor.org/packages/release/bioc/vignettes/VariantAnnotation/inst/doc/VariantAnnotation.pdf  

# Problem 1: Overlaps between genomic regions and copy number alterations. (14 points total)

### Preparation
Load copy number segment results as shown in *2.1 BED format* of *Lecture16_GenomicData.Rmd*. You will use the same file as in the lecture notes, `BRCA.genome_wide_snp_6_broad_Level_3_scna.seg`. Here is code to get you started.

In [6]:
#load packages
suppressPackageStartupMessages({
    library(tidyverse)
    library(GenomicRanges)
    library(plyranges)
    library(VariantAnnotation)
})

In [ ]:
segs <- read.delim("BRCA.genome_wide_snp_6_broad_Level_3_scna.seg", as.is = TRUE)
mode(segs$Chromosome) <- "character" 
segs[segs$Chromosome == 23, "Chromosome"] <- "X"
segs.gr <- as(segs, "GRanges")

segs.gr %>% as_tibble()
# GRanges object (with following columns):
    # seqnames = chromosome names
    # start = start indices of sequence in chromosome (1-based indexing)
    # end = end indices of sequence in chromosome (1-based indexing)
    # width = length from start to end indices
	# strand = + or - strand (or *)
    # Sample (chr) = TCGA IDs (e.g. TCGA-3C-...)
    # Num_Probes (int) = 
    # Segment_Mean (dbl) = deletion, neutral, or gain values

       seqnames start     end       width     strand
1      1          3218610  95674710  92456101 *
2      1         95676511  95676518         8 *
3      1         95680124 167057183  71377060 *
4      1        167057495 167059336      1842 *
5      1        167059760 181602002  14542243 *
6      1        181603120 181609567      6448 *
7      1        181610685 201473647  19862963 *
8      1        201474400 201474544       145 *
9      1        201475220 247813706  46338487 *
10     2           484222  51515129  51030908 *
11     2         51517041  51524666      7626 *
12     2         51525025 242476062 190951038 *
13     3          2212571   2283296     70726 *
14     3          2283337   2285495      2159 *
15     3          2285508  13895817  11610310 *
16     3         13897245  13897406       162 *
17     3         13897885  89268266  75370382 *
18     3         89268644  89268812       169 *
19     3         89269219 197538677 108269459 *
20     4          1053934 162477082 161423149 *
21     4        162477184 162480449      3266 *
22     4        162480911 188763651  26282741 *
23     5           914233  71249846  70335614 *
24     5         71252854  71253149       296 *
25     5         71257317 108310673  37053357 *
26     5        108311484 108314037      2554 *
27     5        108321827 180360469  72038643 *
28     6          1014281 161012443 159998163 *
29     6        161014499 161014935       437 *
30     6        161015250 170903919   9888670 *
⋮      ⋮        ⋮         ⋮         ⋮         ⋮
284429 16       50378387   50409140     30754 *
284430 16       50413232   50896231    483000 *
284431 16       50897293   52478911   1581619 *
284432 16       52479771   52502318     22548 *
284433 16       52503294   53539614   1036321 *
284434 16       53540891   53541478       588 *
284435 16       53544993   53809312    264320 *
284436 16       53810014   56977898   3167885 *
284437 16       56980908   56985139      4232 *
284438 16       56990716   71396135  14405420 *
284439 16       71396172   71396290       119 *
284440 16       71402607   89379936  17977330 *
284441 17         987221   16412342  15425122 *
284442 17       16416773   17967990   1551218 *
284443 17       17970035   18860763    890729 *
284444 17       19152102   31228629  12076528 *
284445 17       31234127   31804569    570443 *
284446 17       31804984   55880090  24075107 *
284447 17       55882611   56164541    281931 *
284448 17       56171979   80917016  24745038 *
284449 18         329586   61806634  61477049 *
284450 18       61809405   61809922       518 *
284451 18       61810012   68327958   6517947 *
284452 18       68337362   68343590      6229 *
284453 18       68347417   77109240   8761824 *
284454 19         284018   58878226  58594209 *
284455 20         455764   62219837  61764074 *
284456 21       15347621   47678774  32331154 *
284457 22       17423930   49331012  31907083 *
284458 X         3157107  154905589 151748483 *
       Sample                       Num_Probes Segment_Mean
1      TCGA-3C-AAAU-10A-01D-A41E-01  53225      0.0055
2      TCGA-3C-AAAU-10A-01D-A41E-01      2     -1.6636
3      TCGA-3C-AAAU-10A-01D-A41E-01  24886      0.0053
4      TCGA-3C-AAAU-10A-01D-A41E-01      3     -1.0999
5      TCGA-3C-AAAU-10A-01D-A41E-01   9213     -0.0008
6      TCGA-3C-AAAU-10A-01D-A41E-01      6     -1.2009
7      TCGA-3C-AAAU-10A-01D-A41E-01  12002      0.0055
8      TCGA-3C-AAAU-10A-01D-A41E-01      2     -1.4235
9      TCGA-3C-AAAU-10A-01D-A41E-01  29781     -0.0004
10     TCGA-3C-AAAU-10A-01D-A41E-01  30300      0.0044
11     TCGA-3C-AAAU-10A-01D-A41E-01     11     -1.1753
12     TCGA-3C-AAAU-10A-01D-A41E-01 100972      0.0041
13     TCGA-3C-AAAU-10A-01D-A41E-01     51      0.0341
14     TCGA-3C-AAAU-10A-01D-A41E-01      2     -1.2873
15     TCGA-3C-AAAU-10A-01D-A41E-01   6969     -0.0065
16     TCGA-3C-AAAU-10A-01D-A41E-01      2     -1.4347
17     TCGA-3C-AAAU-10A-01D-A41E-01  43418     -0.0033
18     TCGA-3C-AAAU-10A-01D-A41E-01      6      0.8839
19     TCGA-3C-AAAU-10A-01D-A41E-01  55921     -0.0034
20     TCGA-3C-AAAU-10A-01D-A41E-01  89190     -0.0037
21     TCGA-3C-AAAU-10A-01D-A41E-01      2     -2.0920
22     TCGA-3C-AAAU-10A-01D-A41E-01  13535     -0.0031
23     TCGA-3C-AAAU-10A-01D-A41E-01  37419      0.0048
24     TCGA-3C-AAAU-10A-01D-A41E-01      2      1.1995
25     TCGA-3C-AAAU-10A-01D-A41E-01  19508     -0.0002
26     TCGA-3C-AAAU-10A-01D-A41E-01      2     -2.0029
27     TCGA-3C-AAAU-10A-01D-A41E-01  43558     -0.0034
28     TCGA-3C-AAAU-10A-01D-A41E-01  91579     -0.0003
29     TCGA-3C-AAAU-10A-01D-A41E-01      5     -0.9912
30     TCGA-3C-AAAU-10A-01D-A41E-01   4896     -0.0061
⋮      ⋮                            ⋮          ⋮
284429 TCGA-Z7-A8R6-01A-11D-A41E-01    13      -0.2206
284430 TCGA-Z7-A8R6-01A-11D-A41E-01   304      -0.8551
284431 TCGA-Z7-A8R6-01A-11D-A41E-01  1201      -0.0861
284432 TCGA-Z7-A8R6-01A-11D-A41E-01    17      -0.7968
284433 TCGA-Z7-A8R6-01A-11D-A41E-01   792      -0.0344
284434 TCGA-Z7-A8R6-01A-11D-A41E-01     5      -0.7512
284435 TCGA-Z7-A8R6-01A-11D-A41E-01   169      -0.0239
284436 TCGA-Z7-A8R6-01A-11D-A41E-01  2295      -0.8173
284437 TCGA-Z7-A8R6-01A-11D-A41E-01     3      -2.9576
284438 TCGA-Z7-A8R6-01A-11D-A41E-01  8086      -0.8084
284439 TCGA-Z7-A8R6-01A-11D-A41E-01     2      -2.9477
284440 TCGA-Z7-A8R6-01A-11D-A41E-01 11807      -0.8337
284441 TCGA-Z7-A8R6-01A-11D-A41E-01  7775      -0.7719
284442 TCGA-Z7-A8R6-01A-11D-A41E-01   742      -0.0520
284443 TCGA-Z7-A8R6-01A-11D-A41E-01   300      -0.7827
284444 TCGA-Z7-A8R6-01A-11D-A41E-01  3435      -0.0533
284445 TCGA-Z7-A8R6-01A-11D-A41E-01   565      -0.8084
284446 TCGA-Z7-A8R6-01A-11D-A41E-01 11551      -0.0508
284447 TCGA-Z7-A8R6-01A-11D-A41E-01   161      -0.7452
284448 TCGA-Z7-A8R6-01A-11D-A41E-01 12426      -0.0470
284449 TCGA-Z7-A8R6-01A-11D-A41E-01 35216      -0.0704
284450 TCGA-Z7-A8R6-01A-11D-A41E-01     2      -2.0272
284451 TCGA-Z7-A8R6-01A-11D-A41E-01  3298      -0.0799
284452 TCGA-Z7-A8R6-01A-11D-A41E-01     9      -0.7669
284453 TCGA-Z7-A8R6-01A-11D-A41E-01  4143      -0.0889
284454 TCGA-Z7-A8R6-01A-11D-A41E-01 23950      -0.1170
284455 TCGA-Z7-A8R6-01A-11D-A41E-01 37283       0.3435
284456 TCGA-Z7-A8R6-01A-11D-A41E-01 20582      -0.1117
284457 TCGA-Z7-A8R6-01A-11D-A41E-01 16927      -0.1231
284458 TCGA-Z7-A8R6-01A-11D-A41E-01 63797       0.0014

### a. Find the segments in `segs.gr` that have *any* overlap with the region `chr8:128,746,347-128,755,810` (4 points)
Print out the first five unique TCGA IDs.

In [ ]:
# create GRanges object for chr8:128,746,347-128,755,810 (MYC gene)
myGRange_1a <- data.frame(seqnames = "8", start = 128746347, end = 128755810) %>% as_granges()

# find overlapping segments between segs.gr and GRanges object
segs.overlap_1a <- find_overlaps(segs.gr, myGRange_1a)

segs.overlap_1a %>% 
  as_tibble() %>% 
  # select Sample (TCGA ID) column
  dplyr::select(Sample) %>%
  # choose unique TCGA IDs
  distinct(Sample) %>% 
  # slice the first five unique TCGA IDs
  dplyr::slice(1:5) %>%
  print()

# A tibble: 5 × 1
  Sample
  <chr>
1 TCGA-3C-AAAU-10A-01D-A41E-01
2 TCGA-3C-AAAU-01A-11D-A41E-01
3 TCGA-3C-AALI-10A-01D-A41E-01
4 TCGA-3C-AALI-01A-11D-A41E-01
5 TCGA-3C-AALJ-10A-01D-A41E-01

### b. Find the mean of the `Segment_Mean` values for copy number segments that have *any* overlap with the region chr17:37,842,337-37,886,915. (4 points)

In [ ]:
# create GRanges object for chr17:37,842,337-37,886,915 (ERBB2 gene)
myGRange_1b <- data.frame(seqnames = "17", start = 37842337, end = 37886915) %>% as_granges()

# find overlapping segments between segs.gr and GRanges object
segs.overlap_1b <- find_overlaps(segs.gr, myGRange_1b)

segs.overlap_1b %>% 
  as_tibble() %>% 
  # select Segment Mean column
  dplyr::select(Segment_Mean) %>%
  # calculate the mean of the values in the Segment Mean column
  summarize(meanSM = mean(Segment_Mean)) %>%
  print()

# A tibble: 1 × 1
  meanSM
   <dbl>
1  0.142

### c. Find the patient sample distribution of copy number for `PIK3CA` (hg19). (6 points)
Find the counts of samples with deletion (D; `Segment_Mean < -0.3`), neutral (N; `Segment_Mean >= -0.3 & Segment_Mean <= 0.3`), gain (G; `Segment_Mean > 0.3`) segments that have `any` overlap with `PIK3CA` gene coordinates.

In [27]:
# look up chromosome number and start and end indices of PIK3CA gene in UCSC Genome Browser on Human (GRCh37/hg19)
# https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr3%3A178865902%2D178957881&hgsid=3426939259_PRI6CyanTdzwAkAnAafQzLrbx4io
# PIK3CA = chr3:178,865,902-178,957,881

# create GRanges object for chr3:178,865,902-178,957,881 (PIK3CA gene)
myGRange_1c <- data.frame(seqnames = "3", start = 178865902, end = 178957881) %>% as_granges()

# find overlapping segments between segs.gr and GRanges object
segs.overlap_1c <- find_overlaps(segs.gr, myGRange_1c)

segs.overlap_1c %>% 
  as_tibble() %>% 
  # create new Segment Type column classifying deletion (D), neutral (N), and gain (G) segments
  mutate(Segment_Type = case_when(Segment_Mean < -0.3 ~ "D",
                                  Segment_Mean >= -0.3 & Segment_Mean <= 0.3 ~ "N",
                                  Segment_Mean > 0.3 ~ "G")) %>%
  # group by Segment Type column
  group_by(Segment_Type) %>%
  # calculate the counts of samples with either deletion (D), neutral (N), and gain (G) in the Segment Type column
  summarize(count = n()) %>%
  print()

# A tibble: 3 × 2
  Segment_Type count
  <chr>        <int>
1 D               17
2 G              185
3 N             2026

# Problem 2: Frequency of copy number alteration events within genomic regions. (12 points total) 

This problem will continue to use the copy number data stored in `segs.gr`.

### a. Create a genome-wide tile of 1Mb windows for the human genome (`hg19`). (6 points)
See *3.1 Tiling the genome* of *Lecture16_GenomicData.Rmd* for hints.

In [ ]:
# using code from Lecture 15
seqinfo <- Seqinfo(genome = "hg19")
seqinfo <- keepStandardChromosomes(seqinfo) 
seqlevelsStyle(seqinfo) <- "NCBI"

slen <- seqlengths(seqinfo) # get the length of the chromosomes
tileWidth <- 1000000 # tile size of 1000 kb (1 Mb)
tiles <- tileGenome(seqlengths = slen, tilewidth = tileWidth,
                    cut.last.tile.in.chrom = TRUE)
tiles

Warning message in (function (seqlevels, genome, new_style) :
“cannot switch some of hg19's seqlevels from UCSC to NCBI style”

GRanges object with 3114 ranges and 0 metadata columns:
         seqnames            ranges strand
            <Rle>         <IRanges>  <Rle>
     [1]        1         1-1000000      *
     [2]        1   1000001-2000000      *
     [3]        1   2000001-3000000      *
     [4]        1   3000001-4000000      *
     [5]        1   4000001-5000000      *
     ...      ...               ...    ...
  [3110]        Y 56000001-57000000      *
  [3111]        Y 57000001-58000000      *
  [3112]        Y 58000001-59000000      *
  [3113]        Y 59000001-59373566      *
  [3114]     chrM           1-16571      *
  -------
  seqinfo: 25 sequences from an unspecified genome

### b. Find the 1Mb window with the most frequent overlapping deletions. (6 points)
Find the 1Mb windows with `any` overlap with deletion copy number segments. Assume a deletion segment is defined as a segment in `segs.gr` having `Segment_Mean < -0.3`. 

Return one of the 1Mb window `Granges` entry with the highest frequency (count) of deletion segments.

Hint: Subset the `segs.gr` to only rows with `Segment_Mean < -0.3`.

In [53]:
# create new segs.gr object that is filtered for only deletion (D) copy number segments
segs.gr_del <- segs.gr %>% 
  as_tibble() %>%
  filter(Segment_Mean < -0.3) %>%
  GRanges()

# find overlapping segments between segs.gr_del (only deletion copy number segments) and 1Mb windows of genome-wide tile
segs.overlap_del <- find_overlaps(tiles, segs.gr_del)

# find the 1Mb window with the highest frequency of deletion segments
most_del <- segs.overlap_del %>%
  as_tibble() %>%
  group_by(seqnames, start, end) %>%
  # calculate the count of deletion segments within each 1Mb window
  summarize(count = n()) %>%
  # sort the counts in descending order so largest counts are at top
  arrange(desc(count)) %>%
  ungroup() %>%
  # slice the first (highest count) 1Mb window (note: top two windows both have 620 counts)
  dplyr::slice(1) %>%
  GRanges() %>%
  print()

`summarise()` has grouped output by 'seqnames', 'start'. You can override using
the `.groups` argument.

GRanges object with 1 range and 1 metadata column:
      seqnames            ranges strand |     count
         <Rle>         <IRanges>  <Rle> | <integer>
  [1]       16 79000001-80000000      * |       620
  -------
  seqinfo: 25 sequences from an unspecified genome; no seqlengths

# Problem 3: Reading and annotating genomic variants (16 points total)

### Preparation

In [54]:
vcfFile <- "GIAB_highconf_v.3.3.2.vcf.gz"
# https://www.bioconductor.org/packages/release/bioc/vignettes/VariantAnnotation/inst/doc/VariantAnnotation.html

### a. Load variant data from VCF file `GIAB_highconf_v.3.3.2.vcf.gz` for `chr8:128,700,000-129,000,000`. (4 points)
Note: use genome build `hg19`.

In [74]:
# using code from Lecture 16
vcfHead <- scanVcfHeader(vcfFile)

# create GRanges object for chr8:128,700,000-129,000,000 (PVT1 gene)
myGRange_3a <- data.frame(seqnames = "8", start = 128700000, end = 129000000) %>% as_granges()

vcf.param <- ScanVcfParam(which = myGRange_3a) 
vcf_3a <- readVcf(vcfFile, genome = "hg19", param = vcf.param)

### b. Combine the fields of the VCF genotype information into a table. (4 points)
You may use your choice of data objects (e.g. `data.frame`).

In [79]:
info(vcf_3a) %>%
  as.data.frame() %>%
  rownames_to_column("ID") %>%
  as_tibble()

    ID                            DPSum platforms platformnames platformbias
1   rs6984323                     NA    4         Illumina....
2   rs4478537                     NA    3         Illumina....
3   rs34141920                    NA    3         Illumina....
4   rs17772814                    NA    4         Illumina....
5   rs77977256                    NA    4         Illumina....
6   8:128715845_AT/A              NA    1             Illumina
7   rs143209301                   NA    3         Illumina....
8   rs202231913                   NA    1             Illumina
9   rs16902340                    NA    4         Illumina....
10  rs7841229                     NA    4         Illumina....
11  rs75797214                    NA    3         CG, Illu....
12  rs72718535                    NA    4         Illumina....
13  rs34040552                    NA    3         Illumina....
14  rs4733548                     NA    4         Illumina....
15  rs16902359                    NA    4         Illumina....
16  rs373242130                   NA    1             Illumina
17  rs16902364                    NA    4         Illumina....
18  rs3824120                     NA    4         Illumina....
19  8:128759740_A/AAAT            NA    2         Illumina....
20  8:128759977_A/ATATTTATT       NA    2         Illumina....
21  rs6470569                     NA    4         Illumina....
22  rs4733550                     NA    4         Illumina....
23  rs6984658                     NA    3         Illumina....
24  rs6470573                     NA    4         Illumina....
25  rs6470574                     NA    4         Illumina....
26  rs6988558                     NA    4         Illumina....
27  rs3931652                     NA    3         Illumina....
28  rs144442792                   NA    3         Illumina....
29  rs12543377                    NA    3         Illumina....
30  rs56288936                    NA    3         Illumina....
⋮   ⋮                             ⋮     ⋮         ⋮             ⋮
279 rs752429                      NA    4         Illumina....
280 rs4733584                     NA    4         Illumina....
281 rs7015112                     NA    4         Illumina....
282 rs6981683                     NA    3         Illumina....
283 rs6981693                     NA    3         Illumina....
284 rs10086182                    NA    4         Illumina....
285 rs59889146                    NA    3         Illumina....
286 rs6470595                     NA    4         Illumina....
287 rs6986528                     NA    3         Illumina....
288 rs7004744                     NA    3         Illumina....
289 rs993725                      NA    4         Illumina....
290 rs4476972                     NA    4         Illumina....
291 rs4733809                     NA    4         Illumina....
292 rs1834620                     NA    3         Illumina....
293 rs10617420                    NA    3         Illumina....
294 rs6470596                     NA    4         Illumina....
295 rs11343602                    NA    3         Illumina....
296 rs11993333                    NA    3         Illumina....
297 rs12334659                    NA    4         Illumina....
298 rs35546489                    NA    2         Illumina....
299 rs4733810                     NA    3         Illumina....
300 rs4733585                     NA    3         Illumina....
301 rs4733811                     NA    4         Illumina....
302 rs4637783                     NA    4         Illumina....
303 rs10956400                    NA    4         Illumina....
304 rs10808563                    NA    4         Illumina....
305 rs71300287                    NA    1             Illumina
306 8:128997155_CTT/C             NA    2         Illumina....
307 8:128997161_TTCTTTCTCTTTCTC/T NA    2         Illumina....
308 rs2392884                     NA    4         Illumina....
    datasets datasetnames datasetsmissingcall callsets callsetnames varType
1   4        HiSeqPE3.... IonExome....        5        HiSeqPE3.... NA
2   3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
3   3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
4   5        HiSeqPE3....     IonExome        6        HiSeqPE3.... NA
5   4        HiSeqPE3.... IonExome....        5        HiSeqPE3.... NA
6   1         HiSeqPE300x CGnormal....        2        HiSeqPE3.... NA
7   3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
8   1         HiSeqPE300x CGnormal....        2        HiSeqPE3.... NA
9   4        HiSeqPE3.... IonExome....        5        HiSeqPE3.... NA
10  4        HiSeqPE3.... IonExome....        5        HiSeqPE3.... NA
11  3        CGnormal.... IonExome....        4        CGnormal.... NA
12  4        HiSeqPE3.... IonExome....        5        HiSeqPE3.... NA
13  3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
14  5        HiSeqPE3....     IonExome        6        HiSeqPE3.... NA
15  5        HiSeqPE3....     IonExome        6        HiSeqPE3.... NA
16  1         HiSeqPE300x CGnormal....        2        HiSeqPE3.... NA
17  4        HiSeqPE3.... IonExome....        5        HiSeqPE3.... NA
18  4        HiSeqPE3.... IonExome....        5        HiSeqPE3.... NA
19  2        HiSeqPE3.... CGnormal....        3        HiSeqPE3.... NA
20  2        HiSeqPE3.... CGnormal....        3        HiSeqPE3.... NA
21  5        HiSeqPE3....     IonExome        6        HiSeqPE3.... NA
22  5        HiSeqPE3....     IonExome        6        HiSeqPE3.... NA
23  3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
24  5        HiSeqPE3....     IonExome        6        HiSeqPE3.... NA
25  4        HiSeqPE3.... IonExome....        5        HiSeqPE3.... NA
26  5        HiSeqPE3....     IonExome        6        HiSeqPE3.... NA
27  3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
28  3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
29  3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
30  3        HiSeqPE3.... CGnormal....        4        HiSeqPE3.... NA
⋮   ⋮        ⋮            ⋮                   ⋮        ⋮            ⋮
279 4        HiSeqPE3.... IonExome....        5        HiSeqPE3.... NA
280 4        HiSeqPE3.... IonExome....        5        HiSeqPE3.... NA
281 4        HiSeqPE3.... IonExome....        5        HiSeqPE3.... NA
282 3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
283 3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
284 5        HiSeqPE3....     IonExome        6        HiSeqPE3.... NA
285 3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
286 5        HiSeqPE3....     IonExome        6        HiSeqPE3.... NA
287 3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
288 3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
289 4        HiSeqPE3.... IonExome....        5        HiSeqPE3.... NA
290 4        HiSeqPE3.... IonExome....        5        HiSeqPE3.... NA
291 5        HiSeqPE3....     IonExome        6        HiSeqPE3.... NA
292 3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
293 3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
294 5        HiSeqPE3....     IonExome        6        HiSeqPE3.... NA
295 3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
296 4        HiSeqPE3.... 10XChrom....        5        HiSeqPE3.... NA
297 4        HiSeqPE3.... IonExome....        5        HiSeqPE3.... NA
298 2        HiSeqPE3.... CGnormal....        3        HiSeqPE3.... NA
299 3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
300 3        HiSeqPE3.... IonExome....        4        HiSeqPE3.... NA
301 5        HiSeqPE3....     IonExome        6        HiSeqPE3.... NA
302 5        HiSeqPE3....     IonExome        6        HiSeqPE3.... NA
303 5        HiSeqPE3....     IonExome        6        HiSeqPE3.... NA
304 5        HiSeqPE3....     IonExome        6        HiSeqPE3.... NA
305 1         HiSeqPE300x CGnormal....        1        HiSeqPE3.... NA
306 2        HiSeqPE3.... CGnormal....        2        HiSeqPE3.... NA
307 2        HiSeqPE3.... CGnormal....        2        HiSeqPE3.... NA
308 4        HiSeqPE3.... IonExome....        5        HiSeqPE3.... NA
    filt         callable     difficultregion arbitrated
1   CS_CGnor.... CS_HiSeq....                 NA
2                CS_HiSeq....                 NA
3   CS_CGnor.... CS_HiSeq.... AllRepea....    NA
4   CS_Solid.... CS_HiSeq....                 NA
5                CS_HiSeq....                 NA
6   CS_CGnor.... CS_HiSeq.... AllRepea....    NA
7                CS_HiSeq....                 NA
8                CS_HiSeq.... AllRepea....    NA
9                CS_HiSeq....                 NA
10               CS_HiSeq.... AllRepea....    NA
11               CS_CGnor....                 NA
12  CS_HiSeq.... CS_HiSeq....                 NA
13  CS_10XGA.... CS_HiSeq.... AllRepea....    NA
14               CS_HiSeq....                 NA
15               CS_HiSeq....                 NA
16               CS_HiSeq.... AllRepea....    NA
17               CS_HiSeq....                 NA
18  CS_10XGA.... CS_HiSeq....                 NA
19               CS_HiSeq.... AllRepea....    NA
20               CS_HiSeq.... AllRepea....    NA
21  CS_HiSeq.... CS_HiSeq....                 NA
22               CS_HiSeq....                 NA
23               CS_HiSeq....                 NA
24  CS_Solid.... CS_HiSeq....                 NA
25  CS_Solid.... CS_HiSeq....                 NA
26               CS_HiSeq....                 NA
27               CS_HiSeq....                 NA
28  CS_CGnor.... CS_HiSeq.... AllRepea....    NA
29               CS_HiSeq....                 NA
30  CS_Solid.... CS_HiSeq.... AllRepea....    NA
⋮   ⋮            ⋮            ⋮               ⋮
279              CS_HiSeq....                 NA
280              CS_HiSeq....                 NA
281              CS_HiSeq....                 NA
282              CS_HiSeq....                 NA
283              CS_HiSeq....                 NA
284              CS_HiSeq....                 NA
285              CS_HiSeq....                 NA
286 CS_HiSeq.... CS_HiSeq.... AllRepea....    NA
287              CS_HiSeq....                 NA
288              CS_HiSeq....                 NA
289              CS_HiSeq....                 NA
290 CS_Solid.... CS_HiSeq....                 NA
291              CS_HiSeq....                 NA
292              CS_HiSeq....                 NA
293              CS_HiSeq.... AllRepea....    NA
294 CS_10XGA.... CS_HiSeq....                 NA
295 CS_10XGA.... CS_HiSeq.... AllRepea....    NA
296              CS_HiSeq....                 NA
297              CS_HiSeq....                 NA
298 CS_HiSeq.... CS_HiSeq.... AllRepea....    NA
299 CS_HiSeq.... CS_HiSeq....                 NA
300 CS_HiSeq.... CS_HiSeq.... SimpleRe....    NA
301 CS_Solid.... CS_HiSeq....                 NA
302              CS_HiSeq....                 NA
303              CS_HiSeq....                 NA
304              CS_HiSeq....                 NA
305              CS_HiSeq.... AllRepea....    NA
306 CS_HiSeq.... CS_HiSeq.... AllRepea....    NA
307 CS_HiSeq.... CS_HiSeq.... AllRepea....    NA
308              CS_HiSeq....                 NA
    callsetwiththisuniqgenopassing callsetwithotheruniqgenopassing
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮   ⋮                              ⋮
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308

### c. Retrieve the following information at chr8:128747953. (8 points)
Print out the SNP ID (i.e. "rs ID"), reference base (`REF`), alterate base (`ALT`), genotype (`GT`), depth (`DP`), allele depth (`ADALL`), phase set (`PS`).

Hints: 

  i. `REF` and `ALT` are in the output of `rowRanges(vcf)`. See Section `3a` in `Lecture16_VariantCalls.ipynb` 
  ii. To get the sequence of `DNAString`, use `as.character(x)`.  
  ii. To get the sequence of `DNAStringSet`, use `as.character(unlist(x))`. 
  iii. To expand a list of information for `geno`, use `unlist(x)`.

In [156]:
# find SNP ID corresponding to position at chr8:128,747,953
snp_id_chr8 <- rowRanges(vcf_3a) %>%
  as.data.frame() %>%
  rownames_to_column("SNP_ID") %>%
  as_tibble() %>%
  # filter for chr8:128,747,953
  filter(seqnames == 8, start == 128747953, end == 128747953) %>%
  dplyr::select(SNP_ID) %>%
  as.character()
  
GT <- geno(vcf_3a)$GT %>% 
  as.data.frame() %>%
  rownames_to_column("SNP_ID") %>%
  as_tibble() %>%
  filter(SNP_ID == snp_id_chr8) %>%
  dplyr::select(HG001) %>%
  as.character()

DP <- geno(vcf_3a)$DP %>% 
  as.data.frame() %>%
  rownames_to_column("SNP_ID") %>%
  as_tibble() %>%
  filter(SNP_ID == snp_id_chr8) %>%
  dplyr::select(HG001) %>%
  as.integer()

ADALL <- geno(vcf_3a)$ADALL %>% 
  as.data.frame() %>%
  rownames_to_column("SNP_ID") %>%
  as_tibble() %>%
  filter(SNP_ID == snp_id_chr8) %>%
  dplyr::select(HG001) %>%
  as.character() %>%
  unlist()

PS <- geno(vcf_3a)$PS %>% 
  as.data.frame() %>%
  rownames_to_column("SNP_ID") %>%
  as_tibble() %>%
  filter(SNP_ID == snp_id_chr8) %>%
  dplyr::select(HG001) %>%
  as.character()

rowRanges(vcf_3a) %>%
  as.data.frame() %>%
  rownames_to_column("SNP_ID") %>%
  as_tibble() %>%
  filter(SNP_ID == snp_id_chr8) %>%
  dplyr::select(SNP_ID, REF, ALT) %>%
  mutate(GT = GT) %>%
  mutate(DP = DP) %>%
  mutate(ADALL = ADALL) %>%
  mutate(PS = PS) %>%
  as.data.frame()

  SNP_ID    REF ALT GT  DP  ADALL                        PS
1 rs3824120 G   T   0|1 461 list(rs3824120 = c(105, 94)) PATMAT